services:
  - type: web
    name: helen-agro-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_KEY
        sync: false
      - key: CLOUD_SECRET
        sync: false
